### ISSUE TITLE
Multiple server support

### ISSUE THREAD

**Issue by debuos512** [SamStudio8/dbot-stats#10]
Add support for use of stats on multiple servers - imagine dbot is in a channel called #42 on both AberWiki and Freenode. All that needs to be done for this is to add another key distinction in the db as to server/connection. Connection string can be garnered from event.server.

**Comment by SamStudio8** [comment]
@reality Multiple server support working, you'll need to manually wrap the servers keys around both the userStats and chanStats dbKeys in db.json;

"aberwiki": { "#42": {...}, "#itonlygetsworse": {...} }
