### ISSUE TITLE
Serious dbot slowdown with large number of knownUsers and aliases

### ISSUE THREAD

**Issue by debuos512** [SamStudio8/dbot-stats#102]
Reaching servers where there are 4000+ knownusers and aliases (yes I know that's silly), we're reaching a point where as such 4000+ regexes are being run every line for the mentions detection. I suggest using channelUsers instead of knownUsers + aliases.Will add API function for retrieving channel users to dbot users dreckly.

**Comment by debuos512** [comment]
Object.keys(dbot.instance.connections['snoonet'].channels['#drugs'].nicks) gets you a list of current nicks in the channel. Then call resolveUser on the hits

**Comment by SamStudio8** [comment]
Downgraded to annoyance after temporary fix.
