### ISSUE TITLE
Redesign Case Discussion 

### ISSUE THREAD

**Issue by debuos512** [SamStudio8/dbot-stats#112]
I'm currently working through implementing databank support (https://github.com/reality/depressionbot/issues/272) for the users module, particularly the API which the stats module makes heavy use of. 

Currently I've got resolveUser down to the following:

``` javascript
'resolveUser': function(server, nick, callback) {
    var user = nick;
    if(this.api.isPrimaryUser(nick)) {
         callback(user);
    } else {
        this.db.search('user', { 'server': server }, function(user) {
            if(_.include(user.aliases, nick)) user = user.primaryNick; 
        }.bind(this), function(err) {
            if(!err) {
                callback(user);
            }
        });
    }
},
```

The point being here that if I were to add useLowerCase support it would be a total butt. Do you think that we should use the impending stats redesign to do away with lowercased nick storage? 

Another thing to note is that in users, and probably in stats too we're going to be using uuids as the key for the data, and 'search' (low-cost) for picking out the records we need.

**Comment by SamStudio8** [comment]
As long since admitted, the issue of casing was the worst design choice I've made for this module, albeit emulating functionality available in other modules at the time. Completion of issue #98 for stats will see an end to this disasterous move once and for all.
