### ISSUE TITLE
Filter user lists to exclude 'dead' users

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/dbot-stats#115]
Allow a `days` parameter to be passed to API methods to exclude the return of user data for users who have not been active for `days` in the channel for which data is being requested.

Related https://github.com/reality/depressionbot/issues/282

**Comment by kevna** [comment]
can you have it get the idle time from the server like /wii to hold with other user data?

**Comment by SamStudio8** [comment]
@Kevna It already calculates idle time on a per-channel basis, given the timestamp of your last received message; http://dbot.oaosidl.org/profile/aberwiki/dent (Hover over the Active/Inactive badges).

**Comment by kevna** [comment]
ah right, I was going to suggest filtering by away status too

**Comment by SamStudio8** [comment]
@Kevna \away isn't particularly well used (on aberwiki at least) and is often an unreliable indicator of whether a user is actually away or not. Instead you can pass a `minutes` parameter to the API (ten minutes is the default) which is used to conclude whether a user is inactive based on the timestamp of their last message.

**Comment by kevna** [comment]
no, as a seperate filter was what I was suggesting
