### ISSUE TITLE
currentNick use for ~inmentions and ~outmentions

### ISSUE THREAD

**Issue by debuos512** [SamStudio8/dbot-stats#128]
There was concern raised at some point with serious slowdown when there are lots of aliases stored within DBot, having to scan every line for use of the nicknames. I want to keep a full list of aliases in the users module, however these stats problems can be allayed by outmentions and inmentions only scanning for uses of user.currentNick - which the new users module keeps track of. This also helps ensure it's an actual nick mention rather than just incidental word use, and we could even go further and only use currentNicks which are currently online. I can make a getCurrentNicks API function in users if this is the path you want to take with this.

**Comment by SamStudio8** [comment]
Related #102 
@reality I quite liked the fact that someone could reference another by an alias and have this still counted against the various counters for mentions (@zuzak -> zuzo) as this felt more fluid (especially if the user was not around at the time). However as we've established this can cause issues in larger networks where nicknames are changed frequently.

Personally I still feel it would be more sensible to automatically remove records for aliases that have not been used in some (perhaps user-determined) amount of time, as I don't really see the requirement for keeping them beyond their lifespan (as per https://github.com/reality/depressionbot/issues/283).

However, given that I seem to remember you were not happy with that solution and I do not want to write anything in the stats API that would duplicate functionality in the users API to try and store the age of an alias, we'll have to try and find a middle ground. Could we store all aliases but mark "recent" ones?
