### ISSUE TITLE
Add commands for mentions data

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/dbot-stats#22]

**Comment by debuos512** [comment]
Now we have harnessed the awesome, unequivocal power of the object sort function, we can quite easily leverage it for showing some interesting data for mentions. I suggest we start with:
- _~outmentions user_ shows most mentioned users by a given user
- _~inmentions user_ shows people who mention given user most
- _~popular_ shows list of most popular users in channel (most mentioned)

**Comment by SamStudio8** [comment]
A+

![welearnedalessontoday](https://f.cloud.github.com/assets/1105722/39709/3301e8ac-553e-11e2-8811-c00c7fa9c58d.jpg)
