### ISSUE TITLE
Inflated ~words count

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/dbot-stats#23]
Currently splits messages on spaces to count the number of words on a line, however arbitrary strings consisting of unnecessary spaces can artificially inflate the metric.

Splitting on spaces is a viable solution given the (albeit minor) overhead that would be required for either:
- Iterating or otherwise filtering the fields of the split message for elements with a length > 0
- Splitting the message with a regular expression

It is however, rather annoying.

@reality, @danharibo: Thoughts?

**Comment by danhedron** [comment]
You can use the Array.filter method.

``` javascript
var words = []; //message exploded on whitespaces.
var countedwords = words.filter(function(w, i, array) { return w.length > 0; });
```

**Comment by debuos512** [comment]
Detect ridiculously high word count in a message, one which could not be reasonable given the input limit (or number of words too close to number of characters?), and respond with something like this:

![](http://atosvictimsgroup.co.uk/wp-content/uploads/2012/12/asshole.jpg)

**Comment by SamStudio8** [comment]
Thanks @danharibo
