### ISSUE TITLE
Usability improvement for result commands

### ISSUE THREAD

**Issue by debuos512** [SamStudio8/dbot-stats#32]
This is what happens:
1. reality types ~loudest, ~verbose or any other leaderboard type command.
2. FiremanSam is all like 'woah son that is amaze i want 2 see what i am but i not in da ledrbord!'
3. First instinct is '~loudest firemansam' 

Of course this just prints out the leaderboard. I suggest something like the following (in ~loudest for example)

``` javascript
if(event.params[1]) {
    event.message = '~lincent ' + event.params[1];
    event.params = event.message.split(' ');
    dbot.instance.emit(event);
}
```

**Comment by SamStudio8** [comment]
Yes this is on my todo list as I was unhappy with the disparity between how
the commands work.
