### ISSUE TITLE
SleepyTime commands

### ISSUE THREAD

**Issue by debuos512** [SamStudio8/dbot-stats#33]
Commands that show:
- How many hours ago a given user went to sleep
- How many hours since a user last slept

Suggest using 'how many hours since' rather than 'went to sleep last at x' to avoid time zone issues

**Comment by SamStudio8** [comment]
Love this idea.
Could have a ~nightowl leaderboard.

**Comment by SamStudio8** [comment]
@reality How should we detect a user has gone to sleep?

**Comment by debuos512** [comment]
Either they log off, or their activity drops off

**Comment by SamStudio8** [comment]
@reality We can't guarantee that is sleep though!

**Comment by SamStudio8** [comment]
Don't think we'll be able to track sleep patterns well enough with the data to hand. Closing for now.
