### ISSUE TITLE
Merge users needs to merge data fields

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/dbot-stats#34]

**Comment by SamStudio8** [comment]
- Implement a merge() function for each field that takes in a copy of another field's this.data and merges it in to that field.
- Merge API will iterate over fields in a user and call the merge.

**Comment by debuos512** [comment]
I've confirmed this is working correctly and producing correct total metrics post-merge through two tests in merging users in a live environment running your code.

**Comment by SamStudio8** [comment]
A+
