### ISSUE TITLE
Currently active functionality

### ISSUE THREAD

**Issue by debuos512** [SamStudio8/dbot-stats#37]
In developing on https://github.com/reality/depressionbot/issues/111 I thought it would be nice to show an 'active' indicator next to online users. This would be in the realm of stats, and I'm not sure whether this information is already stored in the stats database, but the exposed functionality would be an API function in stats with the following configuration options:

_isActive({ server, user, channel, inLast })_
- If user is defined and channel is defined, return if user is active in channel.
- If no user is defined but a channel is, return if channel is active.
- If no channel is defined but a user is, return if user is active among any channels.
- If inLast is not defined, choose reasonable default.

Due to the range of functionality it would be best if this function accepts a configuration object as a parameter. Alternatively you could split this functionality out into different functions (isChannelActive etc) but personally I think the suggested method is 63.4% fancier. Also consider an ~isactive command in stats to expose this functionality to the IRC interface.

This functionality is conducive to [#33].

**Comment by debuos512** [comment]
https://github.com/reality/depressionbot/commit/c28047efc191c1bcd0808aa3a1a2b6585b3c1c64 is ready for your to plug your API function into.

**Comment by debuos512** [comment]
![](http://i2.kym-cdn.com/photos/images/newsfeed/000/117/814/are-you-wizard.jpg)

**Comment by SamStudio8** [comment]
Testing. Working. Wizard.
