### ISSUE TITLE
Visualisations

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/dbot-stats#64]
@reality, @danharibo I've added this issue as a place to store possible viz ideas for the web interface, please add anything you deem sufficiently shiny.

**Comment by SamStudio8** [comment]
- Node graph for in and out mentions
- Activity heatmap for channels and each user

**Comment by danhedron** [comment]
D3 seems like a shiny library, and I think it's been mentioned before.

On 20 January 2013 19:37, Sam Nicholls notifications@github.com wrote:

> - Node graph for in and out mentions
> - Activity heatmap for channels and each user
>   
>   —
>   Reply to this email directly or view it on GitHubhttps://github.com/SamStudio8/stats/issues/64#issuecomment-12475951.

## 

Daniel Evans
Web: http://bytecove.co.uk
Games: http://razor-studios.co.uk

**Comment by SamStudio8** [comment]
@danharibo Yes I've actually gone so far as to include it in depressionbot already - I plan to try it out on a few simple bar charts when I can get to it.

**Comment by debuos512** [comment]
While we want fancy-ass visualisations I also think it would be cool to have some basic stats too just with some simple bar charts. Also useful for scoping out how easy this stuff is going to be.

Maybe view this page for Identica graphs/stats for some ideas of basic functionality like activity over time etc

http://www.macno.org/denticator/?user=reality&service=identi.ca&chart=flash (might take a couple of attempts at loading it, it's been a bit shit recently)

**Comment by SamStudio8** [comment]
@reality This is certainly my intention (See https://github.com/reality/depressionbot/issues/167), I just wanted an issue where feature-level visualizations could be proposed.
