### ISSUE TITLE
More friendly output of ~last command 

### ISSUE THREAD

**Issue by debuos512** [SamStudio8/dbot-stats#74]
It's be cool if the command gave output more like this:

'reality was last seen in #turtles 5 hours ago'
'reality was last seen in #turtles 3 days and 5 hours ago'

**Comment by SamStudio8** [comment]
@reality I've been thinking of how to do this but was holding off to see whether we would be using a third party date/time library.

Related https://github.com/SamStudio8/stats/issues/42

**Comment by SamStudio8** [comment]
@reality http://momentjs.com/docs/#/displaying/from/ What do you think?
