### ISSUE TITLE
Stats broken for aliases in ~loudest

### ISSUE THREAD

**Issue by debuos512** [SamStudio8/dbot-stats#76]
13:13:57 @reality ~loudest
13:13:58 < dbot> Loudest users in #doom since Tue Jan 15 2013: jadetizolam (9.70%), jade (9.70%), trees (7.54%), jate (3.51%), rockerode (2.96%)
13:14:06 @reality oh god what
13:14:11 @reality ~alias jade
13:14:11 < dbot> jade is a primary user with 8 aliases, including: jaded, DrFuckedyourmom, BloodHalfDrunk, jadetizolam.
13:14:17 @reality ~alias jadetizolam
13:14:17 < dbot> jadetizolam is an alias of jade
13:16:26 @reality ~lincent jade
13:16:26 < dbot> jade is responsible for 9.71% (7,708) messages in #doom since Wed Jan 16 2013
13:16:29 @reality ~lincent jadetizolam
13:16:30 < dbot> jade is responsible for 9.71% (7,708) messages in #doom since Wed Jan 16 2013

As you'll notice, ~loudest shows "jadetizolam (9.70%), jade (9.70%)"

Not sure if this is a stats or users problem, but I've opened it here since the ~alias command seems to be showing users as resolving correctly :(

**Comment by SamStudio8** [comment]
Turns out the users NICK listener was not calling stats API to update the keys, closing.
