### ISSUE TITLE
Check for missing database keys on module load

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/dbot-stats#8]
Prevent the module from falling over when trying to access non-existent database keys that have been added to an already deployed version of the module.

**Comment by SamStudio8** [comment]
Options:
- Subdivide the data structure by fields first, rather than users or channels first;
  ie: dbot.db.userStats.aberwiki.Sam["#42"].total_lines -> dbot.db.userStats.aberwiki.lines.Sam["#42"]
  This would prevent having to perform any forms of integrity checking as we just add dbKeys as we go along.
- Perform an integrity check on module load to "fill in" missing dbKeys in both the user and chanStat structures.
  This is a more complicated solution but I feel that the data structure as-is provides a nicer API rather than layering the data by field first.

@reality, @danharibo: Thoughts?

**Comment by danhedron** [comment]
Well using Javascript's getters and setters to provide the per-user-object API, you could do any filling-in on first access, whilst still keeping the information in the easier to validate first option.

[Citation](http://ejohn.org/blog/javascript-getters-and-setters/)

**Comment by SamStudio8** [comment]
@danharibo Do you suggest that I create some sort of proper object class to house the data in and use these getters and setters? I'm confused as to where they would be defined.

**Comment by danhedron** [comment]
Well each known user would just have a proxy object in userStats.network.users, which just contains their username and the network, which is enough to look up the information from the other source.

**Comment by debuos512** [comment]
Actually using classes? WTF? This is

![](http://i.imgur.com/0skrb.jpg)

**Comment by danhedron** [comment]
indeed.

**Comment by SamStudio8** [comment]
Following 6d99949fc1d93e1a93f11ceb31c507247d4ae1c1 I feel a tad like this.

![wholetyoudothis](https://f.cloud.github.com/assets/1105722/44614/10c28756-56d3-11e2-85b2-190d5937ce4f.jpg)

**Comment by SamStudio8** [comment]
@reality @danharibo Closing this for now unless either have suggestions.
