### ISSUE TITLE
Databank

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/dbot-stats#98]
dbot-stats to use databank backend instead of JSON flatfile.

**Comment by SamStudio8** [comment]
- User and channel structure functions to be loaded in from structures.js as previously, but not "attached".
- Internal API (iAPI) will provide a uniform method to lookup and apply the appropriate functions from the structure.
- iAPI will probably provide one of these uniforming methods for each counter intent (add, merge, reset, delete).
- iAPI will house all databank communications, freeing the structure from a particular database implementation.
- iAPI will also be responsible for creating new UserStat and ChanStat records, using the appropriate initial values for each field in the structure.
- User and channel statistic structures to be kept separate as before, using UserStat UUID and ChanStat UUID references to infer relationships where necessary.
- Integrity onLoad will need to check users and channels have stats objects with all fields.

**Comment by SamStudio8** [comment]
@reality LOOK I'M MAKING DECISIONS
![ron-paul](https://f.cloud.github.com/assets/1105722/537206/72bbb3b8-c16a-11e2-8f23-32ae874e35fb.gif)

**Comment by debuos512** [comment]
~flashy green approved
